### PR TITLE
ZPI-71: Added healthchecks

### PR DESCRIPTION
**Pull request by samuelus**

### CODE REVIEW

**Comment by Ninja00Shadow** [comment]
ZPI-71-healthckecks-special-name-for-Dawid? Real vindictive, eh?

**Review by Ninja00Shadow — CHANGES_REQUESTED** [review]
Files look ok, but dockerfile needs to be changed

**Review by Nightbaka — APPROVED** [review]
LGTM

**Comment by samuelus** [comment]
> Files look ok, but dockerfile needs to be changed

Done

**Review by Ninja00Shadow — APPROVED** [review]
wGyOgmhp

**Pull request merged**
